language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required

install:
  - dotnet restore

script:
# Build and Pack Rest
  - dotnet build .\Battlerite.NET.Assets\ --configuration Release
  - dotnet pack .\Battlerite.NET.Assets\ --configuration Release

  - dotnet build .\Battlerite.NET.Rest\ --configuration Release
  - dotnet pack .\Battlerite.NET.Rest\ --configuration Release

  - dotnet build .\Battlerite.NET\ --configuration Release
  - dotnet pack .\Battlerite.NET\ --configuration Release

deploy:
  provider: script
  skip_cleanup: true
  script:
  - dotnet nuget push .\Battlerite.NET.Assets\bin\Release\*.nupkg --source $NUGET_FEEDURL

  - dotnet nuget push .\Battlerite.NET.Rest\bin\Release\*.nupkg --source $NUGET_FEEDURL

  - dotnet nuget push .\Battlerite.NET\bin\Release\*.nupkg --source $NUGET_FEEDURL
  on:
    branch: master