language: csharp
mono: none
dotnet: 2.0.0
dist: trusty
sudo: required



script:
  - dotnet restore Battlerite.NET.sln /p:BuildNumber=$TRAVIS_BUILD_NUMBER
  - dotnet build Battlerite.NET.sln --configuration Release /p:BuildNumber=$TRAVIS_BUILD_NUMBER

  - dotnet pack ./Battlerite.NET.Assets/ --configuration Release --output "../Packets" --no-build /p:BuildNumber=$TRAVIS_BUILD_NUMBER --version-suffix "alpha-$TRAVIS_BUILD_NUMBER"
  - dotnet pack ./Battlerite.NET.Rest/ --configuration Release --output "../Packets" --no-build /p:BuildNumber=$TRAVIS_BUILD_NUMBER --version-suffix "alpha-$TRAVIS_BUILD_NUMBER"
  - dotnet pack ./Battlerite.NET/ --configuration Release --output "../Packets" --no-build /p:BuildNumber=$TRAVIS_BUILD_NUMBER --version-suffix "alpha-$TRAVIS_BUILD_NUMBER"

deploy:
  provider: script
  skip_cleanup: true
  script:
  - cd ./Packets/ && ls && dotnet nuget push Rethought.Battlerite.NET.Assets.*.nupkg -k "$NUGET_KEY" -s "$NUGET_URL" && dotnet nuget push Rethought.Battlerite.NET.Rest.*.nupkg -k "$NUGET_KEY" -s "$NUGET_URL" && dotnet nuget push Rethought.Battlerite.NET.*.nupkg -k "$NUGET_KEY" -s "$NUGET_URL"

  on:
    branch: master